name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:  # id of input
    description: 'github-token'
    required: true
  actions:  # id of input
    description: 'actions'
    required: true
    default:  ''
outputs:
  result: # id of output
    description: 'Random number'
    value: '0'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: baseline-test
      uses: echoiitime-inc/baseline-test@v1.0
      id: baseline-test
      with: 
        python-version: '3.7'
        github-token: ${{ inputs.github-token  }}
    - name: get baseline-test result 
      run: echo ${{ steps.baseline-test.outputs.result }}
      shell: bash
    - name: docker-source-combine
      id: docker-source-combine
      uses: echoiitime-inc/docker-source-combine@v1.0
      with: 
        python-version: '3.7'
        node-version: '16.x'
        case-path: 'success/case1'
        node_env: 'testing'
        jina_hubble_registry: 'jina_hubble_registry'
        github-token: ${{ inputs.github-token }}
    - name: get docker-source-combine result 
      run: echo ${{ steps.docker-source-combine.outputs.result }}
      shell: bash
        